name: News Digest Telegram Bot

on:
  push:
    branches: [main]
  workflow_dispatch:        # manual trigger from GitHub UI
  schedule:
    - cron: "30 1 * * *"   # 7:00 AM IST = 01:30 UTC — triggers digest directly too

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 60      # runs for up to 1 hour (keeps polling alive)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run News Digest Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          NEWS_API_KEY:       ${{ secrets.NEWS_API_KEY }}
          ANTHROPIC_API_KEY:  ${{ secrets.ANTHROPIC_API_KEY }}
        run: python bot.py
